language: node_js
node_js:
- '12'
branches:
  only:
  - master
services:
- docker
apt addons: skip
cache components: skip
before_install:
- openssl aes-256-cbc -K $encrypted_2072747d72b7_key -iv $encrypted_2072747d72b7_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /.ssh/id_rsa -d
- ssh-add /.ssh/id_rsa -d
install: skip
before_script: skip
script:
- docker login -u ${DHUB_USERNAME} -p ${DHUB_PASSSWORD}
- docker build -t joycjay/lol-loupe:dev-front .
before_cache: skip
after_success:
- docker push joycjay/lol-loupe:dev-front
after_failure:
- echo script failed
- ssh ubuntu@42.192.95.242 "echo 3 >> test.log"
