language: node_js
node_js:
- '12'
branches:
  only:
  - master
services:
- docker
addons:
  ssh_known_hosts:
  - 42.192.95.242
# lifecycles
apt addons: skip
cache components: skip
before_install:
- openssl aes-256-cbc -K $encrypted_2072747d72b7_key -iv $encrypted_2072747d72b7_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ~/.ssh/id_rsa
- ssh-add ~/.ssh/id_rsa
install: skip
before_script: skip
script:
- docker login -u ${DHUB_USERNAME} -p ${DHUB_PASSSWORD}
- docker build -t joycjay/lol-loupe:dev-front .
before_cache: skip
after_success:
- docker push joycjay/lol-loupe:dev-front
- ssh ubuntu@42.192.95.242 "date >> test.log"
after_failure:
- echo script failed
